format = """
$directory\
$git_branch\
$git_status\
$fill\
$cmd_duration\
$python\
$line_break\
$character"""

[fill]
symbol = " "

[character]
error_symbol = "[✗](bold red)"

[directory]
read_only = " "
truncation_length = 4
truncation_symbol = "…/"
truncate_to_repo = false

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "bold blue"

[git_status]
# format = '[\[$staged$modified$untracked$up_to_date\]]($style)'
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "bold green"
untracked = "?$style"
modified = "[!](bold yellow)"
staged = "+$style"
deleted = ""
up_to_date = "✓"

[cmd_duration]
format = "[$duration]($style) "
style = "#D0EBE0"

[time]
disabled = false
style = "#B9DBF8"
format = "[$time]($style) "
time_format = "%H:%M"

[python]
symbol = " "
format = "[$symbol$version $virtualenv]($style) "
version_format = "$raw"
detect_folders = []
detect_files = []
detect_extensions = []
style = "#94E69C"